from typing import Any, Dict, Optional
import os
from urllib.parse import quote
from xml.sax.saxutils import escape

from fastapi import APIRouter, Depends, HTTPException, Request, Response
from fastapi.responses import PlainTextResponse
from fastapi.templating import Jinja2Templates
from jinja2 import TemplateNotFound
from sqlalchemy.orm import Session

from .. import models
from ..database import get_db
from fastapi.responses import RedirectResponse 
from .site_collections import get_status, get_live_products

router = APIRouter(tags=["Pages"])
templates = Jinja2Templates(directory="static")


def template_exists(template_name: str) -> bool:
    """Return whether a page template is installed in the configured template directory."""
    try:
        templates.env.get_template(template_name)
        return True
    except TemplateNotFound:
        return False


def render_page(
    request: Request,
    template_name: str,
    context: Optional[Dict[str, Any]] = None,
):
    """Render a page, returning a clean 404 when its template is not deployed yet."""
    try:
        templates.env.get_template(template_name)
    except TemplateNotFound as exc:
        raise HTTPException(
            status_code=404,
            detail=f"Page template '{template_name}' was not found.",
        ) from exc

    return templates.TemplateResponse(
        request=request,
        name=template_name,
        context=context or {},
    )


# IndexNow verification file
@router.get("/ab18ee55ab8d4d5ba822aef73d159ea8.txt", response_class=PlainTextResponse)
def indexnow_key():
    return "ab18ee55ab8d4d5ba822aef73d159ea8"


# Main pages
@router.get("/")
def home_page(request: Request):
    return render_page(request, "index.html")


@router.get("/explore")
def explore_page(request: Request):
    return render_page(request, "explore.html")


@router.get("/category")
def category_page(request: Request):
    return render_page(request, "category.html")


@router.get("/about")
def about_page(request: Request):
    return render_page(request, "about.html")


@router.get("/submit")
def submit_page(request: Request):
    return render_page(request, "submit.html")


@router.get("/nigeria-66")
def nigeria_66_page(request: Request):
    return render_page(request, "nigeria-66.html")


# Nigeria Alternatives listing. /alternative is the canonical URL used by the site;
# /nigeria-alternative is retained as a backward-compatible alias.
@router.get("/alternative")
@router.get("/alternative", include_in_schema=False)
def nigeria_alternatives_page(request: Request):
    return render_page(request, "alternative.html")


# Detail URLs are generated by home.js as /alternative/{slug}. The longer alias
# is included for links/bookmarks that use /nigeria-alternative/{slug}.
@router.get("/alternative/{slug}")
@router.get("/alternative/{slug}", include_in_schema=False)
def nigeria_alternative_detail_page(slug: str, request: Request):
    return render_page(request, "alternative-detail.html")


@router.get("/ai")
def ai_page(request: Request):
    return render_page(request, "ai.html")


@router.get("/contact")
def contact_page(request: Request):
    return render_page(request, "contact.html")


@router.get("/privacy")
def privacy_page(request: Request):
    return render_page(request, "privacy.html")


@router.get("/term")
def term_page(request: Request):
    return render_page(request, "term.html")


@router.get("/guidelines")
def guidelines_page(request: Request):
    return render_page(request, "guidelines.html")


# Future pages: these routes return 404 until their templates are added to static/.
@router.get("/spotlight")
def spotlight_page(request: Request):
    return render_page(request, "spotlight.html")


@router.get("/collection")
def collection_page(request: Request):
    return render_page(request, "collection.html")


# Developer and authentication pages
@router.get("/dashboard")
def dashboard_page(request: Request):
    return render_page(request, "dashboard.html")


@router.get("/login")
def login_page(request: Request):
    return render_page(request, "login.html")


@router.get("/signup")
def signup_page(request: Request):
    return render_page(request, "signup.html")


@router.get("/admin")
def admin_page(request: Request):
    return render_page(request, "admin.html")


# Dynamic Nigerian product page
@router.get("/product/{slug}")
def product_page(slug: str, request: Request, db: Session = Depends(get_db)):
    product = (
        db.query(models.Product)
        .filter(
            models.Product.slug == slug,
            models.Product.status == True,
        )
        .first()
    )

    if not product:
        raise HTTPException(status_code=404, detail="Product not found")

    return render_page(request, "product.html", {"product": product})

@router.get("/alternative/{slug}")
def alternative_detail_page(slug: str, request: Request, db: Session = Depends(get_db)):
    foreign_tool = db.query(models.ForeignTool).filter(models.ForeignTool.slug == slug).first()

    if not foreign_tool:
        raise HTTPException(status_code=404, detail="Foreign tool not found")

    alternatives = (
        db.query(models.Product)
        .join(models.ProductAlternative, models.Product.id == models.ProductAlternative.product_id)
        .filter(
            models.ProductAlternative.foreign_tool_id == foreign_tool.id,
            models.Product.status == True
        )
        .all()
    )

    return templates.TemplateResponse(
        request=request,
        name="alternative_detail.html",
        context={"foreign_tool": foreign_tool, "alternatives": alternatives}
    )
@router.get("/sitemap.xml")
def sitemap(db: Session = Depends(get_db)):
    site_url = os.getenv("SITE_URL", "https://search.enovoxtech.com").rstrip("/")

    # Include only pages whose templates are actually installed. This keeps the
    # future /spotlight and /collection routes out of the sitemap until published.
    public_pages = [
        ("/", "index.html"),
        ("/explore", "explore.html"),
        ("/category", "category.html"),
        ("/about", "about.html"),
        ("/submit", "submit.html"),
        ("/nigeria-66", "nigeria-66.html"),
        ("/alternative", "alternative.html"),
        ("/ai", "ai.html"),
        ("/contact", "contact.html"),
        ("/privacy", "privacy.html"),
        ("/term", "term.html"),
        ("/guidelines", "guidelines.html"),
        ("/spotlight", "spotlight.html"),
        ("/collection", "collection.html"),
    ]

    urls = [
        f"{site_url}{path}"
        for path, template_name in public_pages
        if template_exists(template_name)
    ]

    products = (
        db.query(models.Product)
        .filter(models.Product.status == True)
        .all()
    )
    for product in products:
        if product.slug:
            encoded_slug = quote(str(product.slug), safe="")
            urls.append(f"{site_url}/product/{encoded_slug}")
        # Dedicated collection pages (manual collections with more than 6 live products)
    collections = (
        db.query(models.Collection)
        .filter(models.Collection.is_archived == False, models.Collection.section_type == "manual")
        .all()
    )
    for c in collections:
        if get_status(c) == "live" and len(get_live_products(c, db)) > 6:
            urls.append(f"{site_url}/collection/{quote(str(c.slug), safe='')}")

    # Foreign tool pages that have at least one live Nigerian alternative
    live_tool_ids = (
        db.query(models.ProductAlternative.foreign_tool_id)
        .join(models.Product, models.Product.id == models.ProductAlternative.product_id)
        .filter(models.Product.status == True)
        .distinct()
    )
    tools = db.query(models.ForeignTool).filter(models.ForeignTool.id.in_(live_tool_ids)).all()
    for tool in tools:
        if tool.slug:
            urls.append(f"{site_url}/alternative/{quote(str(tool.slug), safe='')}")
    xml_items = "\n".join(
        f"  <url><loc>{escape(url)}</loc></url>" for url in urls
    )
    xml_content = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{xml_items}\n"
        "</urlset>"
    )
    return Response(content=xml_content, media_type="application/xml")


@router.get("/robots.txt", response_class=PlainTextResponse)
def robots():
    site_url = os.getenv("SITE_URL", "https://search.enovoxtech.com").rstrip("/")
    content = f"User-agent: *\nAllow: /\nSitemap: {site_url}/sitemap.xml"
    return content

@router.get("/collection/{slug}")
def collection_detail_page(slug: str, request: Request, db: Session = Depends(get_db)):
    c = db.query(models.Collection).filter(models.Collection.slug == slug).first()
    if not c or c.section_type != "manual" or get_status(c) != "live":
        return RedirectResponse("/collection", status_code=302)

    products = get_live_products(c, db)
    if len(products) <= 6:
        return RedirectResponse("/collection", status_code=302)

    return templates.TemplateResponse(
        request=request,
        name="collection_detail.html",
        context={"collection": c, "products": products}
    )